[#examples]
= Configuration examples
:imagesdir: media/

Below are some examples of how you can configure the application.

== Google

Example configuration using Google OIDC and standard form based authentication

.com.enonic.app.oidcidprovider.cfg:
[source,properties]
----
autoinit=true
idprovider.google.oidcWellKnownEndpoint=https://accounts.google.com/.well-known/openid-configuration
idprovider.google.clientId=********.apps.googleusercontent.com
idprovider.google.clientSecret=********
idprovider.google.mappings.displayName=@@{userinfo.given_name} @@{userinfo.family_name}
idprovider.google.rules.forceEmailVerification=true
idprovider.google.defaultGroups=group:google:employees
----

== Auth0

Example configuration using Auth0 with autologin supporting websockets

.com.enonic.app.oidcidprovider.cfg:
[source,properties]
----
autoinit=true
idprovider.auth0.oidcWellKnownEndpoint=https://auth.enonic-qa.com/.well-known/openid-configuration
idprovider.auth0.rules.forceEmailVerification=true
idprovider.auth0.autoLogin.wsHeader=true
idprovider.auth0.autoLogin.allowedAudience=https://service.example.com/api
idprovider.auth0.mappings.displayName=@@{userinfo.name}
----

== Okta with groups from claim

Example mapping Okta group names from the `groups` claim to Enonic groups on every login.

.com.enonic.app.oidcidprovider.cfg:
[source,properties]
----
autoinit=true
idprovider.okta.oidcWellKnownEndpoint=https://example.okta.com/.well-known/openid-configuration
idprovider.okta.clientId=********
idprovider.okta.clientSecret=********
idprovider.okta.scopes=profile email groups
idprovider.okta.groups.claim=groups
idprovider.okta.groups.mapping.0.value=Admins
idprovider.okta.groups.mapping.0.group=group:okta:admins
idprovider.okta.groups.mapping.1.value=Developers
idprovider.okta.groups.mapping.1.group=group:okta:devs
----

== Microsoft Entra ID with full group sync

Example mapping Entra group GUIDs to Enonic groups, with `syncMode=sync` so memberships
in the mapped groups always reflect the token (stale memberships are revoked on login).

.com.enonic.app.oidcidprovider.cfg:
[source,properties]
----
autoinit=true
idprovider.entra.oidcWellKnownEndpoint=https://login.microsoftonline.com/<tenant>/v2.0/.well-known/openid-configuration
idprovider.entra.clientId=********
idprovider.entra.clientSecret=********
idprovider.entra.groups.claim=groups
idprovider.entra.groups.mapping.0.value=e89a3118-2e11-4f8c-9b3a-aaaaaaaaaaaa
idprovider.entra.groups.mapping.0.group=group:entra:admins
idprovider.entra.groups.mapping.1.value=b4c2a912-1234-5678-90ab-bbbbbbbbbbbb
idprovider.entra.groups.mapping.1.group=group:entra:developers
idprovider.entra.groups.syncMode=sync
----


